resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/colrich/product-catalog.git
      branch: master

jobs:
  - name: package-product-service
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/product-service/build.yml
