resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/colrich/product-catalog.git
      branch: buildsystem
  - name: deploy-service
    type: cf
    source:
      api: https://api.run.pez.pivotal.io
      username: {{cf-user}}
      password: {{cf-pass}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
  - name: package-product-service
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/product-service/build.yml
    - put: deploy-service
      params: 
        manifest: source-code/product-service/manifest.yml
        path: product-service-artifacts/product-service-0.0.1-SNAPSHOT.jar
  - name: package-photo-service
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/photo-service/build.yml
    - put: deploy-service
      params:
        manifest: source-code/photo-service/manifest.yml
        path: photo-service-artifacts/photo-service-0.0.1-SNAPSHOT.jar
