platform: linux

image_resource:
  type: docker-image
  source:
    repository: sonarqube
    tag: latest

inputs:
  - name: source-code
  
outputs:
  - name: product-service-artifacts
    path: target

run:
  path: "source-code/product-service/mvnw"
  args: ["-f", "source-code/product-service/pom.xml", "package"]

params:
  MAVEN_BASEDIR: source-code/product-service
