platform: linux

image_resource:
  type: docker-image
  source:
    repository: airdock/oracle-jdk
    tag: latest

inputs:
  - name: source-code
  
outputs:
  - name: product-ui-artifacts

run:
  path: "source-code/product-ui/mvnw"
  args: ["-f", "source-code/product-ui/pom.xml", "package", "-DoutputDir=../../product-ui-artifacts/"]

params:
  MAVEN_BASEDIR: source-code/photo-service



