platform: linux

image_resource:
  type: docker-image
  source:
    repository: airdock/oracle-jdk
    tag: latest

inputs:
  - name: source-code
  
outputs:
  - name: photo-service-artifacts

run:
  path: "source-code/photo-service/mvnw"
  args: ["-f", "source-code/photo-service/pom.xml", "package", "-DoutputDir=../../photo-service-artifacts/"]

params:
  MAVEN_BASEDIR: source-code/photo-service



